### ISSUE TITLE
C'est pas bien rempli par ici... 

### ISSUE THREAD

**Issue by MorganKryze** [GuillaumeDorschner/HackMe#1]
déçu

**Comment by GuillaumeDorschner** [comment]
Bonjour @MorganKryze,

Merci pour votre feedback. Pourriez-vous élaborer sur vos préoccupations ? Vos suggestions sont les bienvenues.

Merci,

@GuillaumeDorschner

**Comment by MorganKryze** [comment]
A oe t'a mis de truc mtn

gg
